name: Resolve NPM Upload Code via JFrog CLI

on:
  workflow_dispatch:

jobs:
  upload-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure npm to use Artifactory virtual repo
        run: |
          REGISTRY_URL="${{ secrets.JFROG_URL }}artifactory/crm-npm-dev/"
          npm config set registry "$REGISTRY_URL"
          AUTH_URL=$(echo "$REGISTRY_URL" | sed 's|https://||')
          echo "//${AUTH_URL}:_authToken=${{ secrets.JFROG_PASSWORD }}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      - name: Configure JFrog CLI
        run: |
          jfrog config add art \
            --url=${{ secrets.JFROG_URL }} \
            --access-token=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false
