name: Resolve NPM Upload Code via JFrog CLI

on:
  workflow_dispatch:

jobs:
  upload-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure npm to use Artifactory virtual repo
        run: |
          npm config set registry ${{ secrets.JFROG_URL }}/crm-npm-dev/
          echo "//$(echo ${{ secrets.JFROG_URL }} /crm-npm-dev/| sed 's|https://||'):_authToken=${{ secrets.JFROG_PASSWORD }}" >> ~/.npmrc

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      - name: Configure JFrog CLI
        run: |
          jfrog config add art \
            --url=${{ secrets.JFROG_URL }} \
            --access-token=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false
